### ISSUE TITLE
monocle layout breaks when a window swallowed

### ISSUE THREAD

**Issue by agoodfellow123** [JopStro/bspswallow#10]
Hello there, using bspwm with monocle layout. My problem is when i make a window swallow the new window shows borders which is not expected in monocle layout, opening another window and then closing it fixes it but it always does the same thing. Could you please add a "reload nodes everytime swallow happened if the user is using monocle layout" code?

**Comment by JopStro** [comment]
Just tried it out and can't seem to reproduce, could you provide a more indepth description or prehaps a screenshot or video. I don't use monocle layout myself so this is unfamiliar to me.

**Comment by agoodfellow123** [comment]
I found out that only manjaro version of bspwm does this bug so, arch version is fine. If you still want me to demonstrate I can but everything is ok now.

**Comment by JopStro** [comment]
Ok, most likley then the bug is in manjaros version of bspwm. No need to demonstrate it :smile:.
