### ISSUE TITLE
Can't get it work with lf file manager

### ISSUE THREAD

**Issue by mkblast** [JopStro/bspswallow#18]
I tried everything but couldn't do it any help?

**Comment by JopStro** [comment]
try adding "lf" to your terminals file

**Comment by mkblast** [comment]
> try adding "lf" to your terminals file

Yeah I tried that, but it did't work.

**Comment by mkblast** [comment]
Wait, it work with images,Im using _sxiv_ ,but with anything else not working I'll list what i use
pdf: zathura 
epub: zathura
vids: mpv

**Comment by Sinono3** [comment]
I had this same problem. I was using [lfimg](https://github.com/cirala/lfimg) for image previews, which requires a running a bash script (`lfrun`) to launch lf instead of opening it directly. I solved it by adding bash to the terminals file. Maybe this could work for you?

**Comment by mkblast** [comment]
> I had this same problem. I was using [lfimg](https://github.com/cirala/lfimg) for image previews, which requires a running a bash script (`lfrun`) to launch lf instead of opening it directly. I solved it by adding bash to the terminals file. Maybe this could work for you?

Thanks for the reply.
so Im using zsh so I added zsh to the terminals folder as you said but it did nothing in lf.

**Comment by mkblast** [comment]
Fixed:
I have a custom open command in lf 
`cmd open $xdg-open "$f"`
the way to fix it is to add `xdg-open` to the terminals file

but i found another issue: xev always swallowed even if I add it no noswollow file, I'll open a new issue for this maybe!
