### ISSUE TITLE
Problem with dmenu

### ISSUE THREAD

**Issue by Monklite** [JopStro/bspswallow#4]
I use dmenu often and when I use it to open up something like firefox while my active window is a terminal emulator, it behaves as if I launched it directly from the terminal instead of dmenu, meaning the terminal gets swallowed. Is there a workaround for this such as modifying the keybind command I use for dmenu?

**Comment by JopStro** [comment]
Just had a think and it could be possible to write a short script that kills bspswallow runs dmenu and then reactivates bspswallow (possibly after a node add event).

Something like:
```
killall bspswallow
dmenu_run
bspc subscribe node_add | while read -r event; do
bspswallow & exit
done &
sleep 5
bspswallow & exit
```
(Might not work haven't got my computer on to test it atm, if it doesn't work use setsid -f on the bspswallow commands)

**Comment by JopStro** [comment]
Here's a revised one after a bit of testing
```
killall bspswallow
dmenu_run
while pidof dmenu; do
done
bspc subscribe node_add | while read -r event; do
bspswallow & exit
done
# sleep 2
# bspswallow & exit
```
Use the commented out part instead of the subscibe while loop if you are worried about using dmenu_run and not opening a program that spawns a window.

**Comment by JopStro** [comment]
I'll add a version of the script to the examples directory.

**Comment by Monklite** [comment]
I added the script into my bspwmrc and omitted the dmenu_run line portion of it since it appears that if it is ran once, it will work indefinitely. This is definitely a proper workaround from what I can tell.  

Thank you so much.

**Comment by Monklite** [comment]
Oh actually, it looks like running it breaks swallowing entirely for me. Weird. It looks like I get an error in the while loop.  
```bash
line 9: syntax error near unexpected token 'done'
line 9: 'done'
```

I was able to fix this by changing "do" to "do continue".

I'm curious, why was it able to work for you? I'm using bash as my shell if that helps. I'll marked closed if my fix works for you, I suppose.

**Comment by JopStro** [comment]
I imagine it's due to bash expecting somthing in a while loop (i was using dash), your fix does work so I'll add it to the one in the examples directory.
