### ISSUE TITLE
pidof bspswallow always exits with 1, even if bspswallow is running

### ISSUE THREAD

**Issue by yassine-112** [JopStro/bspswallow#5]
Hi,
In my machine 
`pidof bspswallow`
always exits with 1 even if bspswallow in running (I linked the binary to /usr/local/bin/ btw), and that causes bspswallow to run multiple time as I restart the window manager. 
As I can tell the cause of that is the bspswallow script is running as a argument to /bin/sh and not standalone.
So changing:
`pidof bspswallow || bspswallow &`
with:`
(ps x | grep bspswallow | grep -v grep)  || bspswallow &`
solved the issue for me.

**Comment by JopStro** [comment]
Good find, that just started happening for me too when testing, will update the readme.
