### ISSUE TITLE
Everything is set but bspswallow does not work.

### ISSUE THREAD

**Issue by agoodfellow123** [JopStro/bspswallow#8]
Hello there, first of all here is my bspwmrc: https://www.heypasteit.com/clip/0IUV47
I have noswallow and terminals in my .config/bspwm (terminals has Alacritty)
And bspswallow in my $PATH
From what I understood these are all the things required for this script to work yet it does not.
I have manjaro and kernel 5.4

**Comment by michkjns** [comment]
I just had the exact same problem (albeit on void linux),
I solved it by replacing the call to bspswallow in bspwmrc to use the absolute path, e.g.:
`(ps x | grep bspswallow | grep -v grep) || $HOME/bin/bspswallow &`

Maybe a real restart could have worked too. I'm not sure why but it seems that a reload of bspwm with `bspc wm -r` wasn't sufficient to let the bspwmrc script find bspswallow in $PATH

**Comment by agoodfellow123** [comment]
> I just had the exact same problem (albeit on void linux),
> I solved it by replacing the call to bspswallow in bspwmrc to use the absolute path, e.g.:
> `(ps x | grep bspswallow | grep -v grep) || $HOME/bin/bspswallow &`
> 
> Maybe a real restart could have worked too. I'm not sure why but it seems that a reload of bspwm with `bspc wm -r` wasn't sufficient to let the bspwmrc script find bspswallow in $PATH

Yes this did it! Thank you.
